dist: bionic
language: csharp
solution: etdb-servicebase-aspnet-core.sln
mono: none
dotnet: 2.2.105
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
      if: tag IS present
    - stage: test
      name: run-tests
      services: mongodb
      before_script:
        - sh setup-mongodb-user.sh "$MONGODB_USERNAME" "$MONGODB_PASSWORD"
      script: ./run-tests.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh

